name: NPM publish beta

on:
  push:
    tags:
      # Publish version (tags like: v1.2.3)
      - v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: bash ./scripts/ci/test.sh

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: bash ./scripts/ci/npm-publish.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG_TYPE: beta
